---
substitutions:
  device_name: "slimmelezer"
  device_friendly_name: "SlimmeLezer"
  device_description: "Okosmérő P1 port kiolvasó"

esphome:
  name: ${device_name}
  comment: "${device_description}"
  platform: ESP8266
  esp8266_restore_from_flash: true
  board: d1_mini
  name_add_mac_suffix: false
  project:
    name: zuidwijk.slimmelezer
    version: "2.0"
external_components:
  - source: /config/esphome/components
    components: [dsmr]

wifi:
  # remove leading '#' and fill in your wifi details
  ssid: !secret wifi_ssid 
  password: !secret wifi_password
  domain: .iloilo

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_name}

captive_portal:

# Enable logging
logger:
  baud_rate: 0
  level: INFO
  # logs:
  #   api: INFO
  #   api.service: INFO
  #   sensor: DEBUG
  #   text_sensor: DEBUG
  #   esphome: INFO
  #   ota: INFO
  #   wifi: INFO
  #   captive_portal: INFO
  #   web_server: INFO
  #   uart: INFO
  #   scheduler: INFO

# Enable Home Assistant API
api:

ota:
  platform: esphome

web_server:
  port: 80

uart:
  baud_rate: 115200
  rx_pin: D7
  rx_buffer_size: 3000

dsmr:
  id: dsmr_instance
  crc_check: false
  max_telegram_length: 3000

sensor:
  - platform: dsmr
    energy_delivered:
      name: "Hatásos import energia (+A)"
      accuracy_decimals: 3
    energy_delivered_tariff1:
      name: "Hatásos import energia (+A) - tarifa 1"
      accuracy_decimals: 3
    energy_delivered_tariff2:
      name: "Hatásos import energia (+A) - tarifa 2"
      accuracy_decimals: 3
    # 3-4 egyelőre inaktív (2023.03.27)
    energy_delivered_tariff3:
      name: "Hatásos import energia (+A) - tarifa 3"
      accuracy_decimals: 3
    energy_delivered_tariff4:
      name: "Hatásos import energia (+A) - tarifa 4"
      accuracy_decimals: 3
    power_delivered:
      name: "Pillanatnyi teljesítmény - hatásos vételezett (+A)"
      accuracy_decimals: 3
      id: power_consumed
      on_value:
        - script.execute: update_power_balance
    power_returned:
      name: "Pillanatnyi teljesítmény - hatásos betáplált (-A)"
      accuracy_decimals: 3
      id: power_produced
      on_value:
        - script.execute: update_power_balance
  
    energy_returned:
      name: "Hatásos export energia (-A)"
      accuracy_decimals: 3
    energy_returned_tariff1:
      name: "Hatásos export energia (-A) - tarifa 1"
      accuracy_decimals: 3  
    energy_returned_tariff2:
      name: "Hatásos export energia (-A) - tarifa 2"
      accuracy_decimals: 3  
    # 3-4 egyelőre inaktív (2023.03.27)
    energy_returned_tariff3:
      name: "Hatásos export energia (-A) - tarifa 3"
      accuracy_decimals: 3  
    energy_returned_tariff4:
      name: "Hatásos export energia (-A) - tarifa 4"
      accuracy_decimals: 3
    
    electricity_tariff:
      name: "Aktuális tarifa"
    frequency:
      name: "Frekvencia"
      accuracy_decimals: 2
    absolute_active_energy:
      name: "Hatásos energia kombinált (+A)+(-A)"
 
    voltage_l1:
      name: "Pillanatnyi fázisfeszültség L1"
    voltage_l2:
      name: "Pillanatnyi fázisfeszültség L2"
    voltage_l3:
      name: "Pillanatnyi fázisfeszültség L3"
    current_l1:
      name: "Pillanatnyi áramerősség L1"
      accuracy_decimals: 1
    current_l2:
      name: "Pillanatnyi áramerősség L2"
      accuracy_decimals: 1
    current_l3:
      name: "Pillanatnyi áramerősség L3"
      accuracy_decimals: 1

    instantaneous_power_factor:
      name: "Pillanatnyi teljesítménytényező"
      device_class: power_factor
    instantaneous_power_factor_l1:
      name: "Pillanatnyi teljesítménytényező L1"
      device_class: power_factor
    instantaneous_power_factor_l2:
      name: "Pillanatnyi teljesítménytényező L2"
      device_class: power_factor
    instantaneous_power_factor_l3:
      name: "Pillanatnyi teljesítménytényező L3"
      device_class: power_factor
    
    reactive_power_qi:
      name: "Pillanatnyi meddő teljesítmény (QI)"
      device_class: reactive_power
    reactive_power_qii:
      name: "Pillanatnyi meddő teljesítmény (QII)"
      device_class: reactive_power
    reactive_power_qiii:
      name: "Pillanatnyi meddő teljesítmény (QIII)"
      device_class: reactive_power
    reactive_power_qiv:
      name: "Pillanatnyi meddő teljesítmény (QIV)"
      device_class: reactive_power
    
    energy_positive_reactive:
      name: "Import meddő energia (+R)"
    energy_negative_reactive:
      name: "Export meddő energia (-R)"
    reactive_energy_qi:
      name: "Meddő energia (QI)"
    reactive_energy_qii:
      name: "Meddő energia (QII)"
    reactive_energy_qiii:
      name: "Meddő energia (QIII)"
    reactive_energy_qiv:
      name: "Meddő energia (QIV)"
 # Mérőóra maximális áramerősséghatároló beállítása
    #electricity_threshold_l1:
    #  name: "Limiter határérték L1"
    #electricity_threshold_l2:
    #  name: "Limiter határérték L2"
    #electricity_threshold_l3:
    #  name: "Limiter határérték L3"
 
  - platform: uptime
    name: "SlimmeLezer Uptime"
    device_class: duration
  - platform: wifi_signal
    name: "SlimmeLezer Wi-Fi Signal"
    update_interval: 60s
    
  - platform: template
    name: "Pillanatnyi teljesítmény - hatásos eredő"
    id: power_balance
    unit_of_measurement: kW
    state_class: measurement
    device_class: power
    accuracy_decimals: 3
    
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "SlimmeLezer IP"
      update_interval: 60s
    ssid:
      name: "SlimmeLezer Wi-Fi SSID"
      update_interval: 60s
    bssid:
      name: "SlimmeLezer Wi-Fi BSSID"
      update_interval: 60s
 
  - platform: dsmr
    #identification:
    #  name: "COSEM logikai készüléknév"
    #equipment_id:
    #  name: "Mérő gyáriszám"
    breaker_status:
      name: "Megszakító státusz"
 
  - platform: version
    name: "ESPHome Version"
    hide_timestamp: false
   
script:
  - id: update_power_balance
    mode: single
    then:
      - lambda: |-
          id(power_balance).publish_state(id(power_produced).state-id(power_consumed).state);
